<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <xacro:include filename="arm_frame.xacro"/>


    <xacro:macro name="wheel_link" params="prefix">
      <link name="${prefix}_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
            <material name="red"/>
        </visual>   
        <xacro:cylinder_inertia xyz="0 0 0" rpy="${pi/2} 0 0" m="1"
                                            r="${wheel_radius}" h="${wheel_length}"/>
        <collision>
  19       <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
  20       <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>

             <surface>
                    <contact>
                        <ode>
                            <mu>0.5</mu>
                            <mu2>0.5</mu2>
                        </ode>
                    </contact>
             </surface>
  23    </collision>
      </link>
    </xacro:macro>
    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <xacro:box_inertia xyz="0 0 0.1" rpy="0 0 0" m="3" 
                                        d="${base_length}" w="${base_width}" h="${base_height}"/> 
        <collision>

            <origin xyz="0 0 0.1" rpy="0 0 0"/>
  20      <geometry>
                <box size = "${base_length} ${base_width} ${base_height}"/>
            </geometry>
  23    </collision>
    </link>


    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz= "${-base_length/4.0} ${(base_width/2.0)+(wheel_length/2.0)} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>
    
     




    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz= "${-base_length/4.0} ${-((base_width/2.0)+(wheel_length/2.0))} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="red"/>
        </visual>    
        <xacro:sphere_inertia xyz="0 0 0" rpy="0 0 0" m="0.5"
                                            r="0.05" />
        <collision>

            <origin xyz="0 0 0" rpy="0 0 0"/>
  20        <geometry>
                <sphere radius="0.05"/>
            </geometry>
            <surface>
                <contact>
                    <ode>
                        <mu>0.01</mu>
                        <mu2>0.01</mu2>
                    </ode>
                </contact>
            </surface>
  23    </collision>
    </link>
    
    <joint name="base_caster_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
        <origin xyz= "0.225 0 -0.05" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>

    </joint>

     <joint name="base_armbase_joint" type = "fixed">
        <parent link="base_link"/>
        <child link="arm_base"/>
        <origin xyz="${(base_length/2)-0.05} 0 ${base_height}" rpy="0 0 0"/>
    </joint> 

    <link name="base_footprint"/>
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz= "0 0 0.1" rpy="0 0 0"/>
    </joint>
</robot>





<!-- 
    <joint name="base_armbase_joint" type = "fixed">
        <parent link="base_link"/>
        <child link="arm_base"/>
        <origin xyz="${(base_length/2)-0.05} 0 ${base_height}" rpy="0 0 0"/>
    </joint> -->

    <!-- <link name="second_link">
        <visual>
            <geometry>
                <cylinder radius="0.1" length="0.2"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green"/>
        </visual>    
    </link>

    <joint name="base_second_joint" type="revolute">
        <parent link="base_link"/>
        <child link="second_link"/>
        <origin xyz="0 0 0.2" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi/2}" upper="${pi/2}" effort="100" velocity="100"/>
    </joint> -->

